### PR TITLE
3.0.11 compatibility and reduce the amount of http requests to sfs

### PR DESCRIPTION
**Pull request by mjrider**
I had problems with upgrading to 3.0.11

Further I wanted to reduce the amount of http requests made to stopforumspam. And thus reducing the latency introduced by those http calls.

### CODE REVIEW

**Comment by EXreaction** [comment]
This looks pretty good from first look. Will need to change the minimum requirements to PHP 5.2 though in the install instructions.

I will put testing this out on my to-do list.

**Comment by Potherca** [comment]
:+1:

**Comment by satdav** [comment]
Hello has this been updated

**Comment by mjrider** [comment]
nevermind, phpbb3.1 is out for a while. and this makes no more sense

**Pull request closed without merging**
